// <auto-generated />
namespace iConcerto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _105617012019_DodawanieAppNetUserDoUserDataZlokacja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_105617012019_DodawanieAppNetUserDoUserDataZlokacja));
        
        string IMigrationMetadata.Id
        {
            get { return "201901170956486_105617012019_DodawanieAppNetUserDoUserDataZlokacja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
